[package]
name = "deserialize-backup"
version = "0.1.0"
edition = "2021"

[dependencies]
structopt = "0.3"
seahash = "4.1.0"
rumqttc = { workspace = true }
bytes = "1.10.0"
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.138"