[package]
name = "deserialize-backup"
version = "0.1.0"
edition = "2021"

[dependencies]
disk = { path = "../../disk" }
rumqttc = { git = "https://github.com/bytebeamio/rumqtt" }
structopt = "0.3"
thiserror = "1"
