download_path = "/tmp/uplink/downloads"
persistence_path = "/tmp/uplink/persistence"
enable_remote_shell = true

[builtin_collectors.device_shadow]
interval_seconds = 1

[streams.motor_info]
buffer_size = 1024
persistence = { max_file_size = 2000000, max_file_count = 10 }

[tcp_clients.first_one]
port = 8032
