download_path = "/tmp/uplink/downloads"
persistence_path = "/tmp/uplink/persistence"
enable_remote_shell = true

[builtin_collectors.device_shadow]
interval_seconds = 1

[streams.device_shadow]
buffer_size = 1
persistence = { max_file_size = 102400, max_file_count = 10 }

[tcp_clients.first_one]
port = 8032
actions = [{ "name" = "a" }]