[persistence]
path = "/tmp/uplink"
max_file_size = 104857600 # 100MB
max_file_count = 3

[simulator]
num_devices = 20
gps_paths = "./paths/"
actions = ["update_firmware", "send_file", "lock", "unlock"]
