# TCP Port to connect your applications with uplink
bridge_port = 5555

# MQTT client configuration
# 
# Required Parameters
# - max_packet_size: Maximum packet size acceptable for MQTT messages
# - max_inflight: Maximum number of outgoing QoS 1/2 messages that can be
#                 handled by uplink, at a time, requiring acknowledgedment.
max_packet_size = 102400
max_inflight = 100

# Whitelist of binaries which uplink can spawn as a process
# This makes sure that user is protected against random actions
# triggered from cloud.
actions = ["tunshell"]

# Metrics configurations are available for serializer and streams. By default 
# they are disabled and no metrics will be forwarded to platform. 
# Parameters
# - topic(optional): One can configure to push stats to a specific topic,
#   different from the default by configuring it with this field.
#
# Serializer module can publish associated metrics, to keep track of 
# serializer performance. 
[serializer_metrics]
enabled = true
topic = "/tenants/{tenant_id}/devices/{device_id}/metrics/jsonarray"

# Serializer module can also publishe stream metrics, to keep track of latencies 
# and batch sizes on a per-stream basis.
# NOTE: Leaving this configuration empty like the following tells uplink to enable
# sending metrics, but with default topic string.
[stream_metrics]
enabled = true

# Configuration details associated with uplink's persistent storage module
# which writes publish packets to disk in case of slow or crashed network.
# 
# Required Parameters
# - path: Path to directory where storage writes backups into files.
# - max_file_size: Maximum size upto which single persistence file can grow
# - max_file_count: Maximum number of persistence files allowed
#
# NOTE: Persitence as a whole is an optional feature that is disabled by
# default, i.e. if not inlcuded in configuration.
[persistence]
path = "/tmp/uplink"
max_file_size = 104857600 # 100MB
max_file_count = 3

# Table of pre-configured data streams, specifies streams of data elements that are to
# be collected, batched and forwarded to serializer to then be published onto platform.
#
# Required Parameters
# - buf-size: Number of data points that shall be included in each Publish
# - topic(optional): topic-filter to which data shall be published. If left
#   unconfigured, stream will be created dynamically.
# - flush-period(optional): Duration in seconds after a data point enters the stream
#   and WILL be flushed by collector. Defaults to 60s in case not configured.
#
# In the following config for the device_shadow stream we set buf_size to 1. streams is
# internally constructed as a map of Name -> Config
[streams.device_shadow]
buf_size = 1

# Built-in streams: action status is a special case of stream and should be configured separately,
# outside of the streams map. The action_status stream is used to push progress of Actions in
# execution. This configuration is required or will lead to fallback to default config.
#
# NOTE: Action statuses are expected on a specifc topic as configured in example below.
# This also means that we require a topic to be configured or uplink will error out.
[action_status]
topic = "/tenants/{tenant_id}/devices/{device_id}/action/status"
buf_size = 1

# Configurations for uplink's built-in file downloader, including the actions that can trigger
# a download, the location in file system where uplink will download and store files from the
# provided URL in the payload of download file actions, over HTTP(S). 
# If left unconfigured, downloader will be disabled.
#
# Required Parameters
# - actions: List of actions names that can trigger the downloader
# - path: Location in fs where the files are downloaded into
[downloader]
actions = ["update_firmware", "send_file"]
path = "/var/tmp/ota-file"

# Configurations associated with the system stats module of uplink, if enabled
# system stats such as memory in use and CPU usage will be published onto special.
#
# Required Parameters
# - enabled: A boolean to determine if the feature must be enabled
# - process_names: List of process names that are to be tracked with system stats
# - update_period: Time in seconds between each collection/publish of system stats
[stats]
enabled = false
process_names = ["uplink"]
update_period = 30

# Configurations associated with running uplink in simulator mode, if enabled 
# uplink will push simulated data for device_id 1..=num_devices and respond to any
# actions triggered on the tenant connected to, with progress 0..=100.
# NOTE: uplink bridge will hence be turned off.
#
# Required Parameters
# - num_devices: number of devices to be simulated
# - gps_paths: path to directory containing files with gps paths to be used in simulation
[simulator]
num_devices = 10
gps_paths = "./paths/"
