
action_redirections={update_firmware="install_firmware"}
[tcpapps.1]
port=5050

[downloader]
path="/tmp/uplink/download"
actions=[{name="update_firmware", timeout=310}, {name="send_file"}]

[ota_installer]
path="/tmp/uplink/installer"
actions=[{name="install_firmware", timeout=310}]
uplink_port=5050
